config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show]
  resources :goals
  resources :reports, except: %i[index show]

  get "/profile" => "users#show"

  root "goals#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
# frozen_string_literal: true

class Goal < ApplicationRecord
  belongs_to :user
  has_many :reports

  validates :title, presence: true
  validates :value, presence: true
  validates :unit, presence: true
  validates :user_id, presence: true

  def full_sentence_output
    if end_date
      "#{title} #{value} #{unit} by #{DateOutput.date_output(end_date)}"
    else
      "#{title} #{value} #{unit}"
    end
  end

  def status_class
    status.tr(" ", "-")
  end

  def total_progress
    reports.sum(&:value)
  end

  def progress_percentage
    "#{(total_progress.to_f / value.to_f * 100).to_i}%"
  end

  def days_taken
    (Time.now.to_i - Time.at(created_at).to_i) / (60 * 60 * 24)
  end

  def days_left
    (end_date - Time.zone.today).to_i
  end

  def pace_output
    "#{pace} #{unit} / day" unless days_taken.zero?
  end

  def chart_data
    labels = reports.map { |report| DateOutput.date_output(report.reported_date) }
    data = reports.map(&:value)
    
    ChartBuilder.chart_data(labels, data)
  end

  def chart_options
    ChartBuilder.chart_options("report", self.id)
  end

  def status
    if complete?
      if completed_date?
        if completed_date >= end_date
          "complete on #{DateOutput.date_output(completed_date)}"
        else
          "complete early on #{DateOutput.date_output(completed_date)}"
        end
      else
        "complete"
      end
    elsif estimated_end_date < end_date
      "ahead"
    elsif estimated_end_date == end_date
      "on pace"
    else
      "behind"
    end
  end

  def complete?
    total_progress >= value
  end

  def estimated_end_date
    unless days_taken.zero?
      remainder = value - total_progress

      if remainder.positive? && pace.positive?
        Time.zone.today + (remainder / pace)
      else
        Time.zone.today
      end
    end
    end_date
  end

  private

  def pace
    total_progress / days_taken
  end

  def past_due?
    Date.today > end_date
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :goal

  validates :value, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :goals
  has_many :reports, through: :goals

  def goal_count
    goals.length
  end

  def complete_goal_count
    goals.count(&:complete?)
  end

  def reports_count
    reports.length
  end

  def next_level
    level + 1
  end

  def next_level_base
    Level.level_base(next_level)
  end

  def change_experience(dif)
    new_xp = experience + dif
    if dif.positive?
      self.level = Level.check_level(new_xp)
      self.experience = new_xp
    elsif new_xp > Level.level_base(level)
      self.experience = new_xp
    else
      self.experience = Level.level_base(level)
    end
    save!
  end

  def progress_percentage
    "#{((experience - Level.level_base(level)).to_f / (Level.level_base(next_level) - Level.level_base(level)).to_f * 100).to_i}%"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: %i[show edit update destroy]

  def index
    @goals = Goal.where(user_id: current_user.id) if current_user
  end

  def show; end

  def new
    @goal = Goal.new
  end

  def create
    goal = Goal.new(goal_params)
    goal.title.capitalize!
    goal.unit.downcase!
    goal.user_id = current_user.id

    return redirect_to goals_url, notice: "Goal successfully created." if goal.save
    render :new
  end

  def edit; end

  def update
    return redirect_to @goal, notice: "Goal successfully updated." if @goal.update(goal_params)
    render :edit
  end

  def destroy
    @goal.destroy
    redirect_to goals_url, notice: "Goal successfully deleted."
  end

  private

  def set_goal
    @goal = current_user.goals.find(params[:id])
  end

  def goal_params
    params.require(:goal).permit(:title, :value, :unit, :end_date)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: %i[edit update destroy]
  before_action :set_goals, only: %i[new edit]

  def new
    @report = Report.new
  end

  def edit; end

  def create
    report = Report.new(report_params)

    if ProcessNewReport.process(report, current_user)
      redirect_to goals_path, notice: "Report successfully logged."
    else
      render :new
    end
  end

  def update
    return redirect_to goals_path, notice: "Report successfully updated." if @report.update(report_params)
    render :edit
  end

  def destroy
    @report.destroy
    redirect_to goals_path, notice: "Report successfully deleted."
  end

  private

  def set_report
    @report = current_user.reports.find(params[:id])
  end

  def set_goals
    @goals = Goal.where(user_id: current_user.id) if current_user
  end

  def report_params
    params.require(:report).permit(:reported_date, :value, :alternate_unit, :note, :goal_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/_form.html.haml
= form_with model: @goal, class: 'form goal-form', local: true do |f|
  - if @goal.errors.any?
    #error_explanation
      %h4.negative-color.heading-margin-small
        = pluralize(@goal.errors.count, "error")
        prohibited this goal from being saved:
      %ul.form-error-list
        - @goal.errors.full_messages.each do |msg|
          %li.form-error= msg
  .form-element
    = f.label :title, class: "form-label bold", for: "goal_title"
    = f.text_area :title, class: "form-input", id: "goal_title"
  .form-element
    = f.label :value, class: "form-label bold", for: "goal_value"
    = f.number_field :value, class: "form-input", id: "goal_value"
  .form-element
    = f.label :unit, class: "form-label bold", for: "goal_unit"
    = f.text_field :unit, class: "form-input", id: "goal_unit"
  .form-element
    = f.label :end_date, class: "form-label bold", for: "goal_end_date"
    = f.date_field :end_date, class: "form-input", id: "goal_end_date", min: Date.today
  .form-element
    = f.submit "Let's get started!", class: "btn submit-btn btn-positive"

app/views/goals/edit.html.haml
%section.page.goals-edit-page
  %h2.page-title Edit Goal:
  = render "form"

app/views/goals/index.html.haml
%section.page.goals-all-page
  %h2.page-title Goals:
  %ul.goals-list
    - if @goals
      - if @goals.any?
        - @goals.each do |goal|
          %li.goal-item
            %article.goal
              %header.goal-header
                %h3.goal-title.heading-margin-none= goal.full_sentence_output
                .goal-status
                  %span.label.bold Status:
                  %span{:class => "info #{goal.status_class}"}= goal.status
              - if goal.end_date && !goal.complete?
                .goal-subheader
                  .goal-row.days-left
                    %span.label.bold Days left:
                    %span.info= number_with_delimiter(goal.days_left)
                  - if goal.days_taken > 0
                    .goal-row.days-taken
                      %span.label.bold Days taken:
                      %span.info= number_with_delimiter(goal.days_taken)
                    .goal-row.pace
                      %span.label.bold Pace:
                      %span.info= goal.pace_output
                    .goal-row.estimated-end-date
                      %span.label.bold Estimated end date:
                      %span.info= DateOutput.date_output(goal.estimated_end_date)
              - if goal.report_ids
                - if !goal.complete?
                  .progress
                    .goal-row.total-progress
                      %span.label.bold Total progress:
                      %span.info= goal.total_progress
                    .goal-row.percent-complete
                      %span.label.bold Percent complete:
                      %span.info= goal.progress_percentage
                    .goal-progress-bar{:style => "background-image:linear-gradient(to right, #00aa2a, #00aa2a #{goal.progress_percentage}, transparent #{goal.progress_percentage}, transparent)"}
                - if goal.report_ids.length > 0
                  .reports-list-wrap
                    %h4 Reports:
                    %ul.reports-list
                      - goal.report_ids.each do |report_id|
                        - @report = Report.find(report_id)
                        %li.report
                          .reported-date.light= DateOutput.date_output(@report.reported_date)
                          .report-value
                            = number_with_delimiter(@report.value)
                            = goal.unit
                          .report-actions-wrap
                            = link_to raw('<i class="fa fa-edit btn-icon"></i>'), |
                              edit_report_path(report_id),                        |
                              class: "btn edit-btn btn-warning"
                            = link_to raw('<i class="fa fa-trash btn-icon"></i>'),              |
                              report_path(report_id),                                           |
                              class: "btn delete-btn btn-negative",                             |
                              method: :delete,                                                  |
                              data: { confirm: 'Are you sure you want to delete this report?' }
                      - if !goal.complete?
                        %li.report.center-aligned.btn-report
                          = link_to raw('<i class="fa fa-plus btn-icon"></i>'), |
                            new_report_path({ preselected_goal_id: goal.id }),  |
                            class: "btn new-btn btn-positive"
                    - if goal.report_ids.length > 1
                      = line_chart goal.chart_data, goal.chart_options
              .goal-actions.actions
                - if !goal.complete?
                  = link_to raw('<div class="icon-wrap"><i class="fa fa-plus icon"></i><span class="icon-label"> Add Report</span></div>'), |
                    new_report_path({ preselected_goal_id: goal.id }),                                                                      |
                    class: "goal-action btn btn-round btn-wide btn-medium center-aligned btn-positive"
                = link_to raw('<div class="icon-wrap"><i class="fa fa-eye icon"></i><span class="icon-label"> View</span></div>'), |
                  goal_path(goal.id),                                                                                              |
                  class: "goal-action btn btn-round btn-wide btn-medium center-aligned"
                - if !goal.complete?
                  = link_to raw('<div class="icon-wrap"><i class="fa fa-pencil icon"></i><span class="icon-label"> Edit</span></div>'), |
                    edit_goal_path(goal.id),                                                                                            |
                    class: "goal-action btn btn-round btn-wide btn-medium center-aligned btn-warning"
                = link_to raw('<div class="icon-wrap"><i class="fa fa-trash icon"></i><span class="icon-label"> Delete</span></div>'), |
                  goal_path(goal),                                                                                                     |
                  class: "goal-action btn btn-round btn-wide btn-medium center-aligned btn-negative",                                  |
                  method: :delete,                                                                                                     |
                  data: { confirm: 'Are you sure you want to delete this goal?' } 
      - else
        .no-goals
          Start by #{link_to 'adding a new goal', new_goal_path}.
    - else
      .no-goals
        = link_to 'Sign in', new_user_session_path
        or #{link_to 'register', new_user_registration_path} to see your goals

app/views/goals/new.html.haml
%section.page.goals-new-page
  %h2.page-title New Goal:
  = render "form"

app/views/goals/show.html.haml
%body
  %section.page.goal-page
    %h2.page-title Goal:
    %article.goal
      %header.goal-header
        %h3.goal-title.heading-margin-none= @goal.full_sentence_output
        .goal-status
          %span.label.bold Status:
          %span{:class => "info #{@goal.status_class}"}= @goal.status
      - if @goal.end_date && !@goal.complete?
        .goal-subheader
          .goal-row.days-left
            %span.label.bold Days left:
            %span.info= number_with_delimiter(@goal.days_left)
          - if @goal.days_taken > 0
            .goal-row.days-taken
              %span.label.bold Days taken:
              %span.info= number_with_delimiter(@goal.days_taken)
            .goal-row.pace
              %span.label.bold Pace:
              %span.info= @goal.pace_output
            .goal-row.estimated-end-date
              %span.label.bold Estimated end date:
              %span.info= DateOutput.date_output(@goal.estimated_end_date)
      - if @goal.report_ids
        - if !@goal.complete?
          .progress
            .goal-row.total-progress
              %span.label.bold Total progress:
              %span.info= @goal.total_progress
            .goal-row.percent-complete
              %span.label.bold Percent complete:
              %span.info= @goal.progress_percentage
            .goal-progress-bar{:style => "background-image:linear-gradient(to right, #00aa2a, #00aa2a #{@goal.progress_percentage}, transparent #{@goal.progress_percentage}, transparent)"}
        - if @goal.report_ids.length > 0
          .reports-list-wrap
            %h4 Reports:
            %ul.reports-list
              - @goal.report_ids.each do |report_id|
                - @report = Report.find(report_id)
                %li.report
                  .reported-date.light= DateOutput.date_output(@report.reported_date)
                  .report-value
                    = number_with_delimiter(@report.value)
                    = @goal.unit
                  .report-actions-wrap
                    = link_to raw('<i class="fa fa-edit btn-icon"></i>'), |
                      edit_report_path(report_id),                        |
                      class: "btn edit-btn btn-warning"
                    = link_to raw('<i class="fa fa-trash btn-icon"></i>'),              |
                      report_path(report_id),                                           |
                      class: "btn delete-btn btn-negative",                             |
                      method: :delete,                                                  |
                      data: { confirm: 'Are you sure you want to delete this report?' }
              - if !@goal.complete?
                %li.report.center-aligned.btn-report
                  = link_to raw('<i class="fa fa-plus btn-icon"></i>'), |
                    new_report_path({ preselected_goal_id: @goal.id }), |
                    class: "btn new-btn btn-positive"
            - if @goal.report_ids.length > 1
              = line_chart @goal.chart_data, @goal.chart_options
      .goal-actions.actions
        - if !@goal.complete?
          = link_to raw('<div class="icon-wrap"><i class="fa fa-plus icon"></i><span class="icon-label"> Add Report</span></div>'), |
            new_report_path({ preselected_goal_id: @goal.id }),                                                                     |
            class: "goal-action btn btn-round btn-wide btn-medium center-aligned btn-positive"
          = link_to raw('<div class="icon-wrap"><i class="fa fa-pencil icon"></i><span class="icon-label"> Edit</span></div>'), |
            edit_goal_path(@goal.id),                                                                                           |
            class: "goal-action btn btn-round btn-wide btn-medium center-aligned btn-warning"
        = link_to raw('<div class="icon-wrap"><i class="fa fa-trash icon"></i><span class="icon-label"> Delete</span></div>'), |
          goal_path(@goal),                                                                                                    |
          class: "goal-action btn btn-round btn-wide btn-medium center-aligned btn-negative",                                  |
          method: :delete,                                                                                                     |
          data: { confirm: 'Are you sure?' }

app/views/layouts/_footer.html.haml
%footer.site-footer
  .credit
    Made with
    %i.fa.fa-heart.footer-icon.heart-icon
    by
    = succeed "." do
      %a{:href => "http://danieljauch.com/"} Daniel Jauch
    %a{:href => "https://bitbucket.org/danieljauch/a-little-bit-more/src/master/"} check out the code
    and
    %i.fa.fa-code-fork.footer-icon.fork-icon
    it for yourself.
  .version-number
    v. #{ALittleBitMore::Application::VERSION}

app/views/layouts/_header.html.haml
%header.site-header
  %h1.title
    = link_to 'A Little Bit More', root_path
  - if notice
    .alert.alert-success
      .alter-message= notice
      %button.btn.dismiss-alert-btn.btn-wide.btn-medium.btn-warning
        %i.fa.fa-chevron-up.dismiss-alert-btn-icon
        %span.dismiss-alert-btn-message Dismiss
  - if alert
    .alert.alert-danger
      .alter-message= alert
      %button.btn.dismiss-alert-btn.btn-wide.btn-medium.btn-warning
        %i.fa.fa-chevron-up.dismiss-alert-btn-icon
        %span.dismiss-alert-btn-message Dismiss
  %nav.site-nav
    .mobile-menu-toggle
      %i.fa.fa-bars.mobile-menu-icon
    %ul.menu.site-menu
      - if user_signed_in?
        %li.menu-item
          = link_to 'New Goal', new_goal_path, class: 'menu-link'
        %li.menu-item
          = link_to 'New Report', new_report_path, class: 'menu-link'
        %li.menu-item
          = link_to 'See my progress', goals_path, class: 'menu-link'
        %li.menu-item
          = link_to 'My profile', '/profile', class: 'menu-link'
        %li.menu-item
          = link_to 'Sign out', destroy_user_session_path, method: :delete
      - else
        %li.menu-item
          = link_to 'Sign in', new_user_session_path, class: 'menu-link'
        %li.menu-item
          = link_to 'Register', new_user_registration_path, class: 'menu-link'

app/views/layouts/application.html.haml
!!!
%html.no-js{:lang => "en"}
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{charset: "utf-8"}/
    %meta{content: "ie=edge", "http-equiv" => "x-ua-compatible"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    %title A Little Bit More
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render partial: "layouts/header"
  
    %main.site-main
      = yield
    
    = render partial: "layouts/footer"

app/views/reports/_form.html.haml
= form_with model: @report, class: 'form report-form', local: true do |f|
  - if @report.errors.any?
    #error_explanation
      %h4.negative-color.heading-margin-small
        = pluralize(@goal.errors.count, "error")
        prohibited this goal from being saved:
      %ul.form-error-list
        - @report.errors.full_messages.each do |msg|
          %li.form-error= msg
  - if @goals
    .form-element
      = f.label :goal_id, class: "form-label bold", for: "report_goal_id"
      = f.select :goal_id,                                 |
        @goals.map { |g| [g.full_sentence_output, g.id] }, |
        { selected: params[:preselected_goal_id] },        |
        class: "form-input",                               |
        id: "report_goal_id"
    .form-element
      = f.label :reported_date, class: "form-label bold", for: "report_reported_date"
      = f.date_field :reported_date, class: "form-input", id: "report_reported_date", value: Date.today
    .form-element
      = f.label :value, class: "form-label bold", for: "report_value"
      = f.number_field :value, class: "form-input", id: "report_value"
    .form-element
      = f.label :note, class: "form-label bold", for: "report_note"
      = f.text_area :note, class: "form-input", id: "report_note"
    .form-element
      = f.submit "There's a little bit more!", class: "btn submit-btn btn-positive"
  - else
    .no-goals
      Start by #{link_to 'adding a goal', new_goal_path}.

app/views/reports/edit.html.haml
%section.page.reports-edit-page
  %h2.page-title Edit Report:
  = render "form"

app/views/reports/new.html.haml
%section.page.reports-new-page
  %h2.page-title New Report:
  = render "form"

app/views/users/show.html.haml
%section.page.user-profile-page
  %h2.page-title User stats:
  %section.user-level-banner
    %header.user-level-banner-heading
      %h3.user-level-banner-title.title Your Level
    .user-level-progress-wrap.center-aligned
      %div{:class => "user-level-badge level-#{@user.level}"}= @user.level
      .user-level-progress-bar{:style => "background-image:linear-gradient(to right, #00aa2a, #00aa2a #{@user.progress_percentage}, transparent #{@user.progress_percentage}, transparent)"}
        .user-level-experience{:style => "left: calc(#{@user.progress_percentage} - 1rem)"}= @user.experience
      .user-next-level
        .next-level-label.light Next:
        .next-level-value= @user.next_level
        .next-level-experience.bold.small-spacing= @user.next_level_base
  .user-row.total-goals
    %span.label.bold Total Goals:
    %span.info= @user.goal_count
  .user-row.total-reports
    %span.label.bold Total Reports:
    %span.info= @user.reports_count
  .user-row.complete-goals
    %span.label.bold Complete Goals:
    %span.info= @user.complete_goal_count